title: React.js Lab
description: Learning Lab for Bitcamp React
template:
  name: react.js-lab
  repo: react.js-lab-template
before:
  - type: createPullRequest
    head: bitcamp
    title: 'Week 1: Fixing Bugs in JSX'
    body: 1-0readme.md
  - type: updateBranchProtection
steps:
  - title: 'Q1 React is not defined'
    description: Import the Goods
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
    - type: respond
      with: 1-1importTheGoods.md
  - title: 'Q2 Blank Screen'
    description: Get Here This Instance!
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
    - type: respond
      with: 1-2getHereThisInstances.md
  - title: 'Q3 Nothing was returned from render'
    description: Return From Whence You Came
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
    - type: respond
      with: 1-3returnFromWhenceYouCame.md
  - title: 'Q4 JavaScript not working in JSX'
    description: May I Interject?
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
    - type: respond
      with: 1-4mayIIinterject.md
  - title: 'Q5 Syntax Error! Unexpected Token'
    description: Under One Condition
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
    - type: respond
      with: 1-5underOneCondition.md
  - title: 'Q6 Unterminated JSX contents'
    description: Close the Gates!
    event: issue_comment.created
    link: '{{ repoUrl }}/pull/1'
    actions:
    - type: respond
      with: 1-6closeTheGates.md
tags:
  - React
  - JavaScript
  - Bit Project
  - Web Development
